spring:
  application:
    name: SNCF

path:
  fichierReferentielGares: /path/to/dossiers
  dossierEntreesCAV: /path/to/dossiers
  dossierCAVEnrichisTries: /path/to/dossiers

distance:
    maxkm: 500.00


