spring:
  application:
    name: SNCF

path:
  fichierReferentielGares: /path/to/dossiers/referentiel
  dossierEntreesCAV: /path/to/dossiers/entrees
  dossierCAVEnrichisTries: /path/to/dossiers/sorties

distance:
    maxkm: 500.00


